SiteWeb/Controllers/EchangesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModelsLibrary.Models.Echanges;
using SiteWeb.Services.Interfaces;
using System.Security.Claims;

namespace SiteWeb.Controllers
{
	[Authorize]
	public class EchangesController : Controller
	{
		private readonly IEchangeService _echangeService;

		public EchangesController(IEchangeService echangeService)
		{
            _echangeService = echangeService;
        }

        // GET: EchangesController
        [HttpGet]
        public ActionResult Index()
		{
			return View();
		}

		// GET: EchangesController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

        [HttpGet]
        // GET: EchangesController/Create
        public ActionResult Create(int iduser1, int idjouet1)
		{
            ViewBag.iduser1 = iduser1;
			ViewBag.idjouet1 = idjouet1;
            return View();
		}

        [HttpGet]
       // [ValidateAntiForgeryToken]
        public async Task<IActionResult> ModifiedStatut(int idechange, int idstatut)
        {
            var succes = await _echangeService.ChangeStatutTransaction(idechange, idstatut);

            if (succes)
            return RedirectToAction(nameof(Index));

            ViewBag.ErrorMessage = "une erreur s'est produite au changement du statut";
            return RedirectToAction(nameof(Index));

        }


        // POST: EchangesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([FromForm] EchangeL echangeL)
		{
			try
			{
                int idUser = Convert.ToInt32(User.FindFirst(ClaimTypes.Name)?.Value);
				echangeL.IdUtilisateur2 = idUser;
				echangeL.ModeLivraison1 = 1;
				echangeL.ModePayUtilisateur1 = 1;
                Guid newGuid = Guid.NewGuid();
                echangeL.Reference = newGuid.ToString();
                echangeL.Statut = 1;
				//echangeL.DateInit = DateTime.UtcNow;
				var sussses =  await _echangeService.AddEchange(echangeL);
                if (!sussses)
                {
                    ViewBag.iduser1 = echangeL.IdUtilisateur1;
                    ViewBag.idjouet1 = echangeL.Jouet1;
                    ViewBag.ErrorMessage = "une erreur s'est produite";
                    return View();
                }

				return RedirectToAction(nameof(Index));
 
            }
            catch
			{
				ViewBag.ErrorMessage = "une erreur s'est produite";
                return View();
			}

		}

		// GET: EchangesController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: EchangesController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: EchangesController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: EchangesController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

SiteWeb/Controllers/JouetsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModelsLibrary.Models.Toys;
using SiteWeb.Services.Implementations;
using SiteWeb.Services.Interfaces;
using System.Drawing;
using System.Drawing.Imaging;
using System.Globalization;
using System.Security.Claims;


namespace SiteWeb.Controllers
{
    public class JouetsController : Controller
    {
        private readonly IJouetService _jouetService;
        private readonly IPhotoService _photoService;
        private readonly IEtatJouetService _etatService;
        private readonly ICategorieJouetService _categorieJouetService;
        private readonly IWebHostEnvironment _environment;

        public JouetsController(IWebHostEnvironment environment, IJouetService jouetService,IPhotoService photoService
            ,  IEtatJouetService etatJouetService
            , ICategorieJouetService categorieJouetService) 
        {
            _environment = environment;
            _jouetService = jouetService;
            _photoService = photoService;
            _categorieJouetService = categorieJouetService;
            _etatService = etatJouetService;
        }


        // GET: ToysController
        [HttpGet]
        public async Task<IActionResult> Index()
        {
			var jouets = await _jouetService.GetJouets();
			List<ToyBoxModel> toyBoxModels = new List<ToyBoxModel>();

			if (jouets is not null)
			{
				foreach (var jouet in jouets)
				{
					var photo = (await _photoService.GetPhotoByIdJouet(jouet.Id)).Where(ph => ph.UrlP.Contains("400x400")).FirstOrDefault();
					// if (photo is not null)
					// {
					//     photo.UrlP = photo.UrlP.Replace("600x600", "600x600");

					// }

					toyBoxModels.Add(new ToyBoxModel()
					{
						Id = jouet.Id,
						Nom = jouet.Nom,
						Categorie = jouet.Categorie,
						Prix = jouet.Prix,
						Photo = photo,
						AcceptAchat = jouet.AcceptAchat,
						AcceptTroc = jouet.AcceptTroc,
					});
				}
			}

			return View(toyBoxModels);
        }


		// GET: ToysController
		[HttpGet]
		public async Task<IActionResult> Categorie(string name)
		{
			var jouets = await _jouetService.GetJouetsByNameCategorie(name);
			List<ToyBoxModel> toyBoxModels = new List<ToyBoxModel>();

			if (jouets is not null)
			{
				foreach (var jouet in jouets)
				{
					var photo = (await _photoService.GetPhotoByIdJouet(jouet.Id)).Where(ph => ph.UrlP.Contains("400x400")).FirstOrDefault();
				
					toyBoxModels.Add(new ToyBoxModel()
					{
						Id = jouet.Id,
						Nom = jouet.Nom,
						Categorie = jouet.Categorie,
						Prix = jouet.Prix,
						Photo = photo,
						AcceptAchat = jouet.AcceptAchat,
						AcceptTroc = jouet.AcceptTroc,
					});
				}
			}
			return View(toyBoxModels);
		}

		// GET: ToysController/Details/5
		[HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
                return NoContent();

            var jouet = await _jouetService.GetJouet(id);
            if (jouet is null)
            {
                return NotFound();
            }

            var toy = new Toy() 
            {
                Id = jouet.Id,
                Nom = jouet.Nom,
                Categorie = jouet.Categorie,
                AgeMin = jouet.AgeMin,
                AgeMax = jouet.AgeMax,
                EtatId = jouet.EtatId,
                Descriptions = jouet.Descriptions,
                Proprietaire = jouet.Proprietaire,
                Prix = jouet.Prix,
                //listPhotos = _photoService.GetPhotoByIdJouet(jouet.Id).Result,
                AcceptAchat = jouet.AcceptAchat,
                AcceptTroc = jouet.AcceptTroc,
            };
            return View(toy);
        }

        // GET: ToysController/Create
        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: ToysController/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] Toy toy, [FromForm] List<IFormFile> images)
        {
			try
			{
				if (ModelState.IsValid)
				{
					int idUser = Convert.ToInt32(User.FindFirst(ClaimTypes.Name)?.Value);

					var jouet = new JouetL()
					{
						Id = toy.Id,
						Nom = toy.Nom,
						Categorie = toy.Categorie,
						AgeMin = toy.AgeMin,
						AgeMax = toy.AgeMax,
						EtatId = toy.EtatId,
						Descriptions = toy.Descriptions,
						Proprietaire = idUser,
						Prix = toy.Prix,
						AcceptAchat = toy.AcceptAchat,
						AcceptTroc = toy.AcceptTroc,
						EstPublier = toy.EstPublier

					};

					var jouetAdd = await _jouetService.AddJouet(jouet);
					if (jouetAdd is null)
					{
						ViewBag.ErrorMessage = "Ajout du jouet echouer";
						return View(toy);
					}
					int count = 0;
					bool isFrist = true;

					if (images != null && images.Count > 0)
					{
						foreach (var photo in images)
						{

							if (photo.Length > 0)
							{
								var fileName = Path.GetFileNameWithoutExtension(photo.FileName).Replace(" ", "-");

								fileName += "_" + DateTime.Now.ToString("yyyyMMddHHmmss");

								fileName += Path.GetExtension(photo.FileName);

								var photoL = new PhotoL
								{
									NomPhoto = fileName,
									DescriptionPhoto = "",
									DatePublication = DateTime.UtcNow,
									Jouet = toy.Id
								};
								//DateTime dateTime = DateTime.UtcNow;
								//string dateString = dateTime.ToString("yyyy-MM-ddTHH:mm:ss.fffZ");
								//string dateString = "2023-07-05T05:24:06.313Z";
								///////////////////////////////////////////////
								//DateTime dateTime;
								//if (DateTime.TryParseExact(dateString, "yyyy-MM-ddTHH:mm:ss.fffZ", CultureInfo.InvariantCulture, DateTimeStyles.None, out dateTime))
								//{
								//    // La chaîne a été convertie avec succès en objet DateTime
								//}
								//else
								//{
								//    // La chaîne n'est pas au format attendu
								//}

								//var imagePath = Path.Combine(_environment.WebRootPath, "images", DateTime.Now.ToString("yyyyMM"), fileName);
								//var directoryPath = Path.GetDirectoryName(imagePath);

								var year = DateTime.Now.Year.ToString();
								var month = DateTime.Now.ToString("MMMM");
								var imagePath = Path.Combine(_environment.WebRootPath, "images", year, month, "600x600", "Toys", fileName);
								var relatifPath = (Path.Combine("images", year, month, "600x600", "Toys", fileName)).Replace("\\", "/");
								var directoryPath = Path.GetDirectoryName(imagePath);

								if (!Directory.Exists(directoryPath))
								{
									Directory.CreateDirectory(directoryPath);
								}
								using (var memoryStream = new MemoryStream())
								{
									await photo.CopyToAsync(memoryStream);
									using (var image = new Bitmap(memoryStream))
									{
										var resizedImage = new Bitmap(image, new System.Drawing.Size(600, 600));

										// Enregistrer l'image redimensionnée au format JPEG avec un niveau de qualité spécifié
										var encoder = ImageCodecInfo.GetImageEncoders().First(c => c.FormatID == ImageFormat.Jpeg.Guid);
										var encoderParams = new EncoderParameters(1);
										encoderParams.Param[0] = new EncoderParameter(Encoder.Quality, 75L);
										resizedImage.Save(imagePath, encoder, encoderParams);

										photoL.Taille = (int)new FileInfo(imagePath).Length;
										photoL.Format = photo.ContentType;
										photoL.UrlP = $"/{relatifPath}";
										photoL.Jouet = jouetAdd.Id;
										photoL.Profil = null;
										photoL.Messages = null;

										if (isFrist)
										{
											// Créer une deuxième image redimensionnée en format 100x100 pixels
											var thumbnailImage = new Bitmap(image, new System.Drawing.Size(400, 400));

											// Enregistrer la deuxième image redimensionnée dans le dossier souhaité
											var thumbnailPath = Path.Combine(_environment.WebRootPath, "images", year, month, "400x400", "Toys", fileName);
											var directorythumbnailPath = Path.GetDirectoryName(thumbnailPath);

											if (!Directory.Exists(directorythumbnailPath))
											{
												Directory.CreateDirectory(directorythumbnailPath);
											}
											// Enregistrer l'image redimensionnée au format JPEG avec un niveau de qualité spécifié
											encoder = ImageCodecInfo.GetImageEncoders().First(c => c.FormatID == ImageFormat.Jpeg.Guid);
											encoderParams = new EncoderParameters(1);
											encoderParams.Param[0] = new EncoderParameter(Encoder.Quality, 75L);

											thumbnailImage.Save(thumbnailPath, encoder, encoderParams);
											isFrist = false;
											var photoL2 = new PhotoL
											{
												NomPhoto = fileName,
												DescriptionPhoto = "",
												DatePublication = DateTime.UtcNow,
												Jouet = toy.Id
											};
											var relatifthumbnailPath = (Path.Combine("images", year, month, "400x400", "Toys", fileName)).Replace("\\", "/");

											photoL2.Taille = (int)new FileInfo(imagePath).Length;
											photoL2.Format = photo.ContentType;
											photoL2.UrlP = $"/{relatifthumbnailPath}";
											photoL2.Jouet = jouetAdd.Id;
											photoL2.Profil = null;
											photoL2.Messages = null;
											if (!(await _photoService.AddPhoto(photoL2)))
											{
												count++;
											}
										}

									}
								}

								var isSuccess = await _photoService.AddPhoto(photoL);
								if (!isSuccess)
								{
									count++;
								}
							}
						}
						if (count > 0)
						{
							ViewBag.ErrorMessage = $"l'ajout de {count} photo a echouer";
							return View(toy);
						}
					}
					return RedirectToAction(nameof(Index));
				}

				return View(toy);

				//return RedirectToAction(nameof(Index));
			}
			catch//(Exception ex)
			{
				ViewBag.ErrorMessage = $"Une erreur s'est produit";
				return View();
			}

        }

SiteWeb/Views/Echanges/Create.cshtml
@using SiteWeb.Services.Interfaces;
@using System.Security.Claims;
@model ModelsLibrary.Models.Echanges.EchangeL
@inject IJouetService _jouetService
@inject IModePayementService _modePayementService
@inject IModeLivraisonService _modeLivraisonService
@{
    int idUser = Convert.ToInt32(User.FindFirst(ClaimTypes.Name)?.Value);
    var jouetuser2 = await _jouetService.GetJoutsByIdUtilisateur(idUser);
    var modepay = await _modePayementService.GetModePayements();
    var modelivre = await _modeLivraisonService.GetModeLivraisons();
}
<div class="container margin_60_35">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="write_review">
                <h1>Échange de jouets</h1>
                <form asp-action="Create" asp-controller="Echanges" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    @if (ViewBag.ErrorMessage != null)
                    {
                        <div class="alert alert-danger mx-auto">@ViewBag.ErrorMessage</div>
                    }
                    <div class="form-group">
                        <label asp-for="PrixUtilisateur2" class="form-label">Prix</label>
                        <input asp-for="PrixUtilisateur2" type="number" class="form-control" id="Prix" />
                        <span asp-validation-for="PrixUtilisateur2" class="text-danger"></span>
                    </div>
                    <input type="hidden" asp-for="IdUtilisateur1" value="@ViewBag.iduser1">
                    <input type="hidden" asp-for="Jouet1" value="@ViewBag.idjouet1">
                    <div class="form-group">

                        <label asp-for="Jouet2" class="form-label">Jouet a echanger*</label>
                        <select asp-for="Jouet2" asp-items="@jouetuser2.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Nom })" class="form-control form-select"></select>
                        <span asp-validation-for="Jouet2" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ModePayUtilisateur2" class="form-label">Mode de payment</label>
                        <select asp-for="ModePayUtilisateur2" asp-items="@modepay.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Nom })" class="form-control form-select"></select>
                        <span asp-validation-for="ModePayUtilisateur1" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ModeLivraison2" class="form-label">Catégorie</label>
                        <select asp-for="ModeLivraison2" asp-items="@modelivre.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Nom })" class="form-control form-select"></select>
                        <span asp-validation-for="ModeLivraison2" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn_1">Échanger</button>
                </form>
            </div>
        </div>
    </div>
</div>

SiteWeb/Views/Echanges/Index.cshtml
@using ModelsLibrary.Models.Echanges;
@using SiteWeb.Services.Interfaces;
@using System.Security.Claims;
@inject IJouetService _jouetService
@inject IModePayementService _modePayementService
@inject IModeLivraisonService _modeLivraisonService
@inject IEchangeService _echangeService
@inject IUtilisateurService _utilisateurService
@inject IJouetService _jouetService
@inject IStatutsTransactionService _statutsTransactionService


@{
    int idUser = Convert.ToInt32(User.FindFirst(ClaimTypes.Name)?.Value);
    var modepay = await _modePayementService.GetModePayements();
    var modelivre = await _modeLivraisonService.GetModeLivraisons();
    var echanges = await _echangeService.GetEchangesByIdUser(idUser);
}
<div class="container margin_60_35">
        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger mx-auto">@ViewBag.ErrorMessage</div>
        }
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col"> iD</th>
                    <th scope="col">vendeur</th>
                    <th scope="col">acheteur</th>
                    <th scope="col">Jouet vendeur</th>
                    <th scope="col">Jouet acheteur</th>
                    <th scope="col">Prix acheteur</th>
                    <th scope="col">Statut</th>
                    <th scope="col">livraison acheteur</th>
                    <th scope="col">Pay acheteur</th>
                    <th scope="col">date</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var echange in echanges)
                {
                    <tr>
                        <th scope="row">@echange.Id</th>
                        <td>
                            @{
                                var vendeur = await _utilisateurService.GetUtilisateur((int)echange.IdUtilisateur1);
                            }
                            <a asp-action="Profil" asp-controller="Utilisateurs" asp-route-id="@vendeur.Id">
                                @vendeur.Nom @vendeur.Prenom

                            </a>
                        </td>
                        <td>
                            @{
                                var achateur = await _utilisateurService.GetUtilisateur((int)echange.IdUtilisateur2);
                            }
                        <a asp-action="Profil" asp-controller="Utilisateurs" asp-route-id="@achateur.Id">
                                @achateur.Nom @achateur.Prenom

                            </a>
                        </td>
                        <td>
                            @{
                                var jouetVendeur = await _jouetService.GetJouet((int)echange.Jouet1);
                            }
                            <a asp-action="Details" asp-controller="Jouets" asp-route-id="@jouetVendeur.Id">
                                @jouetVendeur.Nom

                            </a>
                        </td>
                        <td>
                            @{
                                var jouetAcheteur = await _jouetService.GetJouet((int)echange.Jouet2);
                            }
                            <a asp-action="Details" asp-controller="Jouets" asp-route-id="@jouetAcheteur.Id">
                                @jouetAcheteur.Nom

                            </a>
                        </td>
                        <td>
                            @echange.PrixUtilisateur2.ToString().Replace(",0000","")
                        </td>
                        <td>
                            @{
                                var statut = await _statutsTransactionService.GetStatutsTransaction((int)echange.Statut);
                            }
                            @statut.Nom
                        </td>
                        <td>
                            @{
                                var livraison = await _modeLivraisonService.GetModeLivraison((int)echange.ModeLivraison2);
                            }
                            @livraison.Nom
                        </td>
                        <td>
                            @{
                                var paiement = await _modePayementService.GetModePayement((int)echange.ModePayUtilisateur2);
                            }
                            @paiement.Nom
                        </td>
                        <td>

                            @echange.DateInit
                        </td>
                        <td>
                            <div class="dropdown">
                                <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Changer le statut
                                </button>
                                <ul class="dropdown-menu">
                                    <li><h6 class="dropdown-header">Changer le statut</h6></li>
                                    <li><a class="dropdown-item" asp-action="ModifiedStatut" asp-controller="Echanges" asp-route-idechange="@echange.Id" asp-route-idstatut="3">annulée</a></li>

                                    @if (idUser == echange.IdUtilisateur1)
                                    {
                                        <li><a class="dropdown-item" asp-action="ModifiedStatut" asp-controller="Echanges" asp-route-idechange="@echange.Id" asp-route-idstatut="2">validée</a></li>
                                        <li><a class="dropdown-item" asp-action="ModifiedStatut" asp-controller="Echanges" asp-route-idechange="@echange.Id" asp-route-idstatut="4">remboursée</a></li>
                                        <li><a class="dropdown-item" asp-action="ModifiedStatut" asp-controller="Echanges" asp-route-idechange="@echange.Id" asp-route-idstatut="5">expédiée</a></li>
                                    }
                                    else
                                    {
                                        <li><a class="dropdown-item" asp-action="ModifiedStatut" asp-controller="Echanges" asp-route-idechange="@echange.Id" asp-route-idstatut="6">reçue</a></li>
                                        <li><a class="dropdown-item" asp-action="ModifiedStatut" asp-controller="Echanges" asp-route-idechange="@echange.Id" asp-route-idstatut="7">payée</a></li>
                                    }
                                </ul>
                            </div>
                        </td>
                    </tr>
                }

            </tbody>

        </table>

</div>

SiteWeb/Views/Echanges/_ListeEchanges.cshtml
@model IEnumerable<ModelsLibrary.Models.Echanges.EchangeDetailModel>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Reference)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateInit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateConfirmation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTransfert)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Statut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RaisonAnnulation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdUtilisateur1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdUtilisateur2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrixUtilisateur1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrixUtilisateur2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModeLivraison1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModeLivraison2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModePayUtilisateur1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModePayUtilisateur2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Jouet1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Jouet2)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reference)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateInit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateConfirmation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTransfert)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Statut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RaisonAnnulation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdUtilisateur1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdUtilisateur2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrixUtilisateur1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrixUtilisateur2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModeLivraison1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModeLivraison2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModePayUtilisateur1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModePayUtilisateur2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Jouet1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Jouet2)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>