SiteWeb/Controllers/JouetsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModelsLibrary.Models.Toys;
using SiteWeb.Services.Implementations;
using SiteWeb.Services.Interfaces;
using System.Drawing;
using System.Drawing.Imaging;
using System.Globalization;
using System.Security.Claims;


namespace SiteWeb.Controllers
{
    public class JouetsController : Controller
    {
        private readonly IJouetService _jouetService;
        private readonly IPhotoService _photoService;
        private readonly IEtatJouetService _etatService;
        private readonly ICategorieJouetService _categorieJouetService;
        private readonly IWebHostEnvironment _environment;

        public JouetsController(IWebHostEnvironment environment, IJouetService jouetService,IPhotoService photoService
            ,  IEtatJouetService etatJouetService
            , ICategorieJouetService categorieJouetService) 
        {
            _environment = environment;
            _jouetService = jouetService;
            _photoService = photoService;
            _categorieJouetService = categorieJouetService;
            _etatService = etatJouetService;
        }


        // GET: ToysController
        [HttpGet]
        public async Task<IActionResult> Index()
        {
			var jouets = await _jouetService.GetJouets();
			List<ToyBoxModel> toyBoxModels = new List<ToyBoxModel>();

			if (jouets is not null)
			{
				foreach (var jouet in jouets)
				{
					var photo = (await _photoService.GetPhotoByIdJouet(jouet.Id)).Where(ph => ph.UrlP.Contains("400x400")).FirstOrDefault();
					// if (photo is not null)
					// {
					//     photo.UrlP = photo.UrlP.Replace("600x600", "600x600");

					// }

					toyBoxModels.Add(new ToyBoxModel()
					{
						Id = jouet.Id,
						Nom = jouet.Nom,
						Categorie = jouet.Categorie,
						Prix = jouet.Prix,
						Photo = photo,
						AcceptAchat = jouet.AcceptAchat,
						AcceptTroc = jouet.AcceptTroc,
					});
				}
			}

			return View(toyBoxModels);
        }


		// GET: ToysController
		[HttpGet]
		public async Task<IActionResult> Categorie(string name)
		{
			var jouets = await _jouetService.GetJouetsByNameCategorie(name);
			List<ToyBoxModel> toyBoxModels = new List<ToyBoxModel>();

			if (jouets is not null)
			{
				foreach (var jouet in jouets)
				{
					var photo = (await _photoService.GetPhotoByIdJouet(jouet.Id)).Where(ph => ph.UrlP.Contains("400x400")).FirstOrDefault();
				
					toyBoxModels.Add(new ToyBoxModel()
					{
						Id = jouet.Id,
						Nom = jouet.Nom,
						Categorie = jouet.Categorie,
						Prix = jouet.Prix,
						Photo = photo,
						AcceptAchat = jouet.AcceptAchat,
						AcceptTroc = jouet.AcceptTroc,
					});
				}
			}
			return View(toyBoxModels);
		}

		// GET: ToysController/Details/5
		[HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
                return NoContent();

            var jouet = await _jouetService.GetJouet(id);
            if (jouet is null)
            {
                return NotFound();
            }

            var toy = new Toy() 
            {
                Id = jouet.Id,
                Nom = jouet.Nom,
                Categorie = jouet.Categorie,
                AgeMin = jouet.AgeMin,
                AgeMax = jouet.AgeMax,
                EtatId = jouet.EtatId,
                Descriptions = jouet.Descriptions,
                Proprietaire = jouet.Proprietaire,
                Prix = jouet.Prix,
                //listPhotos = _photoService.GetPhotoByIdJouet(jouet.Id).Result,
                AcceptAchat = jouet.AcceptAchat,
                AcceptTroc = jouet.AcceptTroc,
            };
            return View(toy);
        }

        // GET: ToysController/Create
        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: ToysController/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] Toy toy, [FromForm] List<IFormFile> images)
        {
			try
			{
				if (ModelState.IsValid)
				{
					int idUser = Convert.ToInt32(User.FindFirst(ClaimTypes.Name)?.Value);

					var jouet = new JouetL()
					{
						Id = toy.Id,
						Nom = toy.Nom,
						Categorie = toy.Categorie,
						AgeMin = toy.AgeMin,
						AgeMax = toy.AgeMax,
						EtatId = toy.EtatId,
						Descriptions = toy.Descriptions,
						Proprietaire = idUser,
						Prix = toy.Prix,
						AcceptAchat = toy.AcceptAchat,
						AcceptTroc = toy.AcceptTroc,
						EstPublier = toy.EstPublier

					};

					var jouetAdd = await _jouetService.AddJouet(jouet);
					if (jouetAdd is null)
					{
						ViewBag.ErrorMessage = "Ajout du jouet echouer";
						return View(toy);
					}
					int count = 0;
					bool isFrist = true;

					if (images != null && images.Count > 0)
					{
						foreach (var photo in images)
						{

							if (photo.Length > 0)
							{
								var fileName = Path.GetFileNameWithoutExtension(photo.FileName).Replace(" ", "-");

								fileName += "_" + DateTime.Now.ToString("yyyyMMddHHmmss");

								fileName += Path.GetExtension(photo.FileName);

								var photoL = new PhotoL
								{
									NomPhoto = fileName,
									DescriptionPhoto = "",
									DatePublication = DateTime.UtcNow,
									Jouet = toy.Id
								};
								//DateTime dateTime = DateTime.UtcNow;
								//string dateString = dateTime.ToString("yyyy-MM-ddTHH:mm:ss.fffZ");
								//string dateString = "2023-07-05T05:24:06.313Z";
								///////////////////////////////////////////////
								//DateTime dateTime;
								//if (DateTime.TryParseExact(dateString, "yyyy-MM-ddTHH:mm:ss.fffZ", CultureInfo.InvariantCulture, DateTimeStyles.None, out dateTime))
								//{
								//    // La chaîne a été convertie avec succès en objet DateTime
								//}
								//else
								//{
								//    // La chaîne n'est pas au format attendu
								//}

								//var imagePath = Path.Combine(_environment.WebRootPath, "images", DateTime.Now.ToString("yyyyMM"), fileName);
								//var directoryPath = Path.GetDirectoryName(imagePath);

								var year = DateTime.Now.Year.ToString();
								var month = DateTime.Now.ToString("MMMM");
								var imagePath = Path.Combine(_environment.WebRootPath, "images", year, month, "600x600", "Toys", fileName);
								var relatifPath = (Path.Combine("images", year, month, "600x600", "Toys", fileName)).Replace("\\", "/");
								var directoryPath = Path.GetDirectoryName(imagePath);

								if (!Directory.Exists(directoryPath))
								{
									Directory.CreateDirectory(directoryPath);
								}
								using (var memoryStream = new MemoryStream())
								{
									await photo.CopyToAsync(memoryStream);
									using (var image = new Bitmap(memoryStream))
									{
										var resizedImage = new Bitmap(image, new System.Drawing.Size(600, 600));

										// Enregistrer l'image redimensionnée au format JPEG avec un niveau de qualité spécifié
										var encoder = ImageCodecInfo.GetImageEncoders().First(c => c.FormatID == ImageFormat.Jpeg.Guid);
										var encoderParams = new EncoderParameters(1);
										encoderParams.Param[0] = new EncoderParameter(Encoder.Quality, 75L);
										resizedImage.Save(imagePath, encoder, encoderParams);

										photoL.Taille = (int)new FileInfo(imagePath).Length;
										photoL.Format = photo.ContentType;
										photoL.UrlP = $"/{relatifPath}";
										photoL.Jouet = jouetAdd.Id;
										photoL.Profil = null;
										photoL.Messages = null;

										if (isFrist)
										{
											// Créer une deuxième image redimensionnée en format 100x100 pixels
											var thumbnailImage = new Bitmap(image, new System.Drawing.Size(400, 400));

											// Enregistrer la deuxième image redimensionnée dans le dossier souhaité
											var thumbnailPath = Path.Combine(_environment.WebRootPath, "images", year, month, "400x400", "Toys", fileName);
											var directorythumbnailPath = Path.GetDirectoryName(thumbnailPath);

											if (!Directory.Exists(directorythumbnailPath))
											{
												Directory.CreateDirectory(directorythumbnailPath);
											}
											// Enregistrer l'image redimensionnée au format JPEG avec un niveau de qualité spécifié
											encoder = ImageCodecInfo.GetImageEncoders().First(c => c.FormatID == ImageFormat.Jpeg.Guid);
											encoderParams = new EncoderParameters(1);
											encoderParams.Param[0] = new EncoderParameter(Encoder.Quality, 75L);

											thumbnailImage.Save(thumbnailPath, encoder, encoderParams);
											isFrist = false;
											var photoL2 = new PhotoL
											{
												NomPhoto = fileName,
												DescriptionPhoto = "",
												DatePublication = DateTime.UtcNow,
												Jouet = toy.Id
											};
											var relatifthumbnailPath = (Path.Combine("images", year, month, "400x400", "Toys", fileName)).Replace("\\", "/");

											photoL2.Taille = (int)new FileInfo(imagePath).Length;
											photoL2.Format = photo.ContentType;
											photoL2.UrlP = $"/{relatifthumbnailPath}";
											photoL2.Jouet = jouetAdd.Id;
											photoL2.Profil = null;
											photoL2.Messages = null;
											if (!(await _photoService.AddPhoto(photoL2)))
											{
												count++;
											}
										}

									}
								}

								var isSuccess = await _photoService.AddPhoto(photoL);
								if (!isSuccess)
								{
									count++;
								}
							}
						}
						if (count > 0)
						{
							ViewBag.ErrorMessage = $"l'ajout de {count} photo a echouer";
							return View(toy);
						}
					}
					return RedirectToAction(nameof(Index));
				}

				return View(toy);

				//return RedirectToAction(nameof(Index));
			}
			catch//(Exception ex)
			{
				ViewBag.ErrorMessage = $"Une erreur s'est produit";
				return View();
			}

        }

SiteWeb/Controllers/MessagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModelsLibrary.Models.Users;
using SiteWeb.Services.Interfaces;
using System.Security.Claims;

namespace SiteWeb.Controllers
{
	[Authorize]
	//[ValidateAntiForgeryToken]
	public class MessagesController : Controller
	{
		private readonly IMessageService _messageService;
		public MessagesController( IMessageService messageService) 
		{ 
			_messageService = messageService;
		}
		// GET: MessagesController
		public async Task<IActionResult> Index()
		{
            int idUser = Convert.ToInt32(User.FindFirst(ClaimTypes.Name)?.Value);
            var listconversations = await _messageService.GetAllConversationByIdUtilisateur(idUser);
			return View(listconversations);
		}

		// GET: MessagesController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

        [ValidateAntiForgeryToken]
        // GET: MessagesController/Create
        public ActionResult Create()
		{
			return View();
		}

		// POST: MessagesController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int idjouet,int idUser,string message,string nature)
		{
            if (ModelState.IsValid)
            {
                int exp = Convert.ToInt32(User.FindFirst(ClaimTypes.Name)?.Value);
				var corpmessage = string.Empty;

				if (!string.IsNullOrWhiteSpace(nature))
                {
					corpmessage = $"<a asp-controller=\"{nature}\" asp-action=\"Details\" asp-route-id=\"{idjouet}\"> {message} </a>";
				}
				else
				{
					corpmessage = nature;
				}

				MessageL messageL = new MessageL() { 
									Contenu = corpmessage,
									IdExpediteur = exp,
									IdDestinataire = idUser,
									Id = 0,
									DateM = DateTime.Now,
				};
				var isReussit = await _messageService.AddMessage(messageL);
                return Json(new
                {
                    date = isReussit
				});
            }
			else
			{
				return NoContent();
			}
        }


		// POST: MessagesController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> EnvoyerMessage(int idUser, string message)
		{
			if (!string.IsNullOrWhiteSpace(message))
			{
				int exp = Convert.ToInt32(User.FindFirst(ClaimTypes.Name)?.Value);

				MessageL messageL = new MessageL()
				{
					Contenu = message,
					IdExpediteur = exp,
					IdDestinataire = idUser,
					Id = 0,
					DateM = DateTime.Now,
				};
				var isReussit = await _messageService.AddMessage(messageL);
				return Json(new
				{
					reussit = isReussit,
				});
			}
			else
			{
				return Json(new
				{
					reussit = false,
				});
			}
		}

		// GET: MessagesController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: MessagesController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: MessagesController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: MessagesController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

SiteWeb/Views/Utilisateurs/Create.cshtml
@model UtilisateurL

@{
    ViewData["Title"] = "Create";

    //Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Utilisateur</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
           @* <div class="form-group">
                <label asp-for="MotDePasse" class="control-label"></label>
                <input asp-for="MotDePasse" class="form-control" />
                <span asp-validation-for="MotDePasse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sel" class="control-label"></label>
                <input asp-for="Sel" class="form-control" />
                <span asp-validation-for="Sel" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VilleUser" class="control-label"></label>
                <input asp-for="VilleUser" class="form-control" />
                <span asp-validation-for="VilleUser" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuatierUser" class="control-label"></label>
                <input asp-for="QuatierUser" class="form-control" />
                <span asp-validation-for="QuatierUser" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Points" class="control-label"></label>
                <input asp-for="Points" class="form-control" />
                <span asp-validation-for="Points" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreation" class="control-label"></label>
                <input asp-for="DateCreation" class="form-control" />
                <span asp-validation-for="DateCreation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateDerniereConnexion" class="control-label"></label>
                <input asp-for="DateDerniereConnexion" class="form-control" />
                <span asp-validation-for="DateDerniereConnexion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatutId" class="control-label"></label>
                <input asp-for="StatutId" class="form-control" />
                <span asp-validation-for="StatutId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

SiteWeb/Views/Utilisateurs/Delete.cshtml
@model UtilisateurL

@{
  //  Layout = null;
    ViewData["Title"] = "Delete";

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Utilisateur</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
     @*   <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotDePasse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotDePasse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sel)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VilleUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VilleUser)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuatierUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuatierUser)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Points)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Points)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDerniereConnexion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDerniereConnexion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StatutId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatutId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

SiteWeb/Views/Utilisateurs/Profil.cshtml
@model UserProfil;
@{
	ViewData["Title"] = "Profil";
	//Layout = "~/Views/StatutUser/Create.cshtml";
}

<div class="container">
	<div class="pd-ltr-20 xs-pd-20-10">
		<div class="min-height-200px">
			<div class="row">
				<div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 mb-30">
					<div class="pd-20 card-box height-100-p">
						<div class="profile-photo">
							<a href="modal"
							   data-toggle="modal"
							   data-target="#modal"
							   class="edit-avatar">
								<i class="fa fa-pencil"></i>
							</a>
							<img src="~/DeskapAdmin/vendors/images/photo1.jpg"
								 alt=""
								 class="avatar-photo" />
							<div class="modal fade"
								 id="modal"
								 tabindex="-1"
								 role="dialog"
								 aria-labelledby="modalLabel"
								 aria-hidden="true">
								<div class="modal-dialog modal-dialog-centered"
									 role="document">
									<div class="modal-content">
										<div class="modal-body pd-5">
											<div class="img-container">
												<img id="image"
													 src="~/DeskapAdmin/vendors/images/photo2.jpg"
													 alt="Picture" />
											</div>
										</div>
										<div class="modal-footer">
											<input type="submit"
												   value="Update"
												   class="btn btn-primary" />
											<button type="button"
													class="btn btn-default"
													data-dismiss="modal">
												Close
											</button>
										</div>
									</div>
								</div>
							</div>
						</div>
@*  						 					@Html.HiddenFor(model => model.utilisateur.Id)
 *@
						@try
						{
							<input type="hidden" name="Id" value="@Model.utilisateur.Id" />

						}
						catch (Exception ex)
						{

							Console.WriteLine(ex.Message);
						}

						<div class="profile-info">
							<h5 class="mb-20 h5 text-blue">Profil</h5>
							@if (!(await AuthorizationService.AuthorizeAsync(User, "ProfileAccessPolicy")).Succeeded)
							{
								<form id="sendmessageuser" asp-controller="Messages" asp-action="EnvoyerMessage" method="post">
									<div class="form-group">
										<input placeholder="Ecrivez votre message" class="form-control" name="message" required />
										<div id="messageeuure"> </div>
									</div>
									<button type="submit" class="btn_1">Envoyer message</button>
								</form>
							}
							<partial name="_DetailUserProfil" model="@Model.utilisateur" />
						</div>
					</div>
				</div>
				<div class="col-xl-8 col-lg-8 col-md-8 col-sm-12 mb-30">
					<div class="card-box height-100-p overflow-hidden">
						<div class="profile-tab height-100-p">
							<div class="tab height-100-p">
								<ul class="nav nav-tabs customtab" role="tablist">
									<li class="nav-item">
										<a class="nav-link"
										   data-toggle="tab" href="#jouets" role="tab" id="jouetsTab">Jouets</a>
									</li>
									<li class="nav-item">
										<a class="nav-link"
										   data-toggle="tab" href="#annonces" role="tab" id="annoncesTab">Annonces</a>

									</li>
									@if ((await AuthorizationService.AuthorizeAsync(User, "ProfileAccessPolicy")).Succeeded)
									{
									@* 	<li class="nav-item">
											<a class="nav-link active" data-toggle="tab"
											   href="#echange"
											   role="tab">Echanges</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" data-toggle="tab"
											   href="#achat" role="tab">Achats</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" data-toggle="tab"
											   href="#editer" role="tab">Editer le profil</a>
										</li> *@
									}

								</ul>
								@{
									int idProfil = Model.utilisateur.Id;
								}

								<div class="tab-content">
									<div class="tab-pane" id="jouets" role="tabpanel">
										@* liste jouets*@

										@if ((await AuthorizationService.AuthorizeAsync(User, "ProfileAccessPolicy")).Succeeded)
										{
											<a asp-action="Create" asp-controller="Jouets" class="btn_1" style="margin:10px;"> Ajouter </a>
										}
@* 										<div class="container margin_30" id="listejouets"> </div>
										*@					
										<div style="margin:10px;">
											<partial name="_jouetsList" model="idProfil" />
										</div>

									</div>
									<div class="tab-pane" id="annonces" role="tabpanel">
										@* liste annonces*@

										@if ((await AuthorizationService.AuthorizeAsync(User, "ProfileAccessPolicy")).Succeeded)
										{
											<a asp-action="Create" asp-controller="Annonces" class="btn_1" style="margin:10px;"> Ajouter </a>
										}
										 @* <div class="container margin_30" id="listeAnnonce"> </div> *@
										<div style="margin:10px;">
											<partial name="_AnnoncesList" model="idProfil" />

										 </div>
									</div>
@* 									<div class="tab-pane fade " id="echange" role="tabpanel">
  										<partial name="_EchangeList" />
  									</div>
									<div class="tab-pane fade" id="achat" role="tabpanel">
 										<partial name="_AchatList" />
 									</div>
									<div class="tab-pane fade height-100-p" id="editer">
										 									<partial name="_EditerProfil" />
										
									</div> *@
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

	<script src="~/DeskapAdmin/vendors/scripts/core.js"></script>
  	<script src="~/js/profil.js"></script>  

SiteWeb/Views/Utilisateurs/_AchatList.cshtml
@using ModelsLibrary.Models.Achats
@* @model List<AchatL>
 *@
@if ((await AuthorizationService.AuthorizeAsync(User, "ProfileAccessPolicy")).Succeeded)
{
	

}